# Generated by Django 5.1.2 on 2024-11-11 10:09

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_bb_price_alter_bb_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='price_actual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[bboard.models.validate_even], verbose_name='Цена актуальная'),
        ),
    ]
