# Generated by Django 5.1.2 on 2025-01-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_child_icecream_revrubric_boutique_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='сontent',
        ),
        migrations.AddField(
            model_name='icecream',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание мороженного'),
        ),
    ]
