# Generated by Django 5.1.2 on 2025-01-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_remove_icecream_сontent_icecream_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boutique',
            old_name='icereams',
            new_name='icecreams',
        ),
    ]
