# Generated by Django 5.1.2 on 2025-01-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_icecream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
