# Generated by Django 5.1.2 on 2025-01-22 10:39

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='img',
            field=models.ImageField(blank=True, upload_to=bboard.models.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
