# Generated by Django 5.1.2 on 2025-01-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_doc_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='img',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
