# Generated by Django 5.1.2 on 2025-01-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_doc_desc_alter_img_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='doc',
            new_name='file',
        ),
    ]
