# Generated by Django 5.1.2 on 2025-01-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_message_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaPrivateMessage',
            fields=[
                ('privatemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.privatemessage')),
                ('priority', models.IntegerField(default=1)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
            options={
                'ordering': ['-priority', '-published'],
            },
            bases=('testapp.privatemessage',),
        ),
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ['-published']},
        ),
    ]
